### ISSUE TITLE
Girders

### ISSUE THREAD

**Issue by fernandohds564** [lnls-fac/sirius#15]
How can we get the girder information of the accelerator?

I thought we could have markers in the lattice delimiting the beginning and end of each girder (like in AT) and a function which reads the lattice and returns a dictionary with the girder names (e.g. '001','002' and so on) as keys and lists of indices of each girder as values.

What do @xresende , @afonsoharuo and @LuanaVilela think about it?

I don't know exactly where to define this function, though.

**Comment by fernandohds564** [comment]
Maybe we could get the girders information from the _get_family_data_ function, as another key to the dictionary.

**Comment by xresende** [comment]
@fernandohds564 , I read the issue you raised and logged in github to suggest exactly what you already had suggested. I never liked the idea of introducing markers in the lattice just for delimiting purposes. I believe that having girder delimiters as markers or as additional element fields (as is done with AT) is not fundamentally more appropriate than having the equivalent info stored in a separate function, such as  _get_family_data_ mentioned by you.

**Comment by fernandohds564** [comment]
But I think we do need the markers, because it would be very difficult to create a function which can generate the girders info from an accelerator object without them.

**Comment by fernandohds564** [comment]
We've decided to keep the girders and return the girder information together with the _get_family_data_ output.
