### ISSUE TITLE
Export function get_family_data

### ISSUE THREAD

**Issue by fernandohds564** [lnls-fac/sirius#16]
I don't think it is a good idea to export the _family_data_ dictionary. Instead, it would be better to export the function _get_family_data_, because sometimes we change the number of elements of the accelerator, for example when we insert ids in the model, which will break the information in the dictionary, created when the module is imported.

What do you think, @afonsoharuo , @xresende , @LuanaVilela ?

**Comment by xresende** [comment]
Igreed.
