### ISSUE TITLE
Add reasonable excitation curves

### ISSUE THREAD

**Issue by afonsoharuo** [lnls-fac/sirius#9]
Add files and names to mapping in excitation_curves.py.

**Comment by xresende** [comment]
maybe add generalized excitation curves already.

**Comment by afonsoharuo** [comment]
A question: what should it return when asked for a conversion outside the table range, or should it raise an exception?

**Comment by afonsoharuo** [comment]
Added. User values from 3D magnet model field analyses when available, estimated otherwise.
